### ISSUE TITLE
Animation doesnt work even if you copy paste the exact code.

### ISSUE THREAD

**Issue by jainam240101** [react-spring/react-spring-examples#34]

**Comment by aleclarson** [comment]
What example did you try, and with which `react-spring` version?

**Comment by jainam240101** [comment]
Hey Alec so  I tried using react-spring version **8.0.27** and tried making 2
animations, one is **SVG DASHOFFSET* *(
https://www.react-spring.io/docs/props/spring ) and another one us *Card
Stack *(https://www.react-spring.io/docs/hooks/use-springs). I tried
referring to the Code Sandbox as a reference but the thing is it
doesnt animate it just displays there, so can you please help me out cause
I want to implement React-Spring on my projects.
I hope to get a reply from you soon.

**Comment by jainam240101** [comment]
> What example did you try, and with which `react-spring` version?

Hey,so i tried using react-spring version **8.0.27**

**Comment by aleclarson** [comment]
v8 is not maintained currently. You can try using v9 beta:
```
npm install react-spring@next
```
If that doesn't help, please upload your attempt to Github and paste the link here. 👍

**Comment by VivekNeel** [comment]
Hi @aleclarson : You can try : https://github.com/VivekNeel/Drag-Drop 

Uses 

   ``` "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "react-spring": "^9.0.0-beta.34",
    "react-use-gesture": "^7.0.14"```

**Comment by VivekNeel** [comment]
How would you handle the dynamic height if the listitem is of varying height?

**Comment by jainam240101** [comment]
Alec the v9 beta version shows error of Render Props like it cant resolve its not able to find it out.

**Comment by aleclarson** [comment]
@jainam240101 Did you try this?
```ts
import { Spring } from 'react-spring'
```

**Comment by zroper** [comment]
I'm experiencing the same issue where the diagram won't animate. In react-spring version 8, the transitions fire on click, but are not animated. In version 9, mouse click results in no change to the diagram at all.

**Comment by aleclarson** [comment]
@zroper Please [open a new issue](https://github.com/react-spring/react-spring/issues/new), with a sandbox (you can use [this template](https://codesandbox.io/s/nifty-fog-8ebn2?file=/src/App.js) if you want).
