### ISSUE TITLE
Diagram won't animate when using react-spring v9

### ISSUE THREAD

**Issue by zroper** [react-spring/react-spring-examples#36]
Here is a [code sandbox](https://codesandbox.io/s/nervous-lichterman-ghuyj?file=/src/index.js) that replicates the issue.

**Comment by aleclarson** [comment]
That example is made for v8. To get it working in v9, rename the `onFrame` prop to `onChange`.

**Comment by zroper** [comment]
Beautiful! Thank you kindly.
