### ISSUE TITLE
basic typescript examples

### ISSUE THREAD

**Issue by dcsan** [react-spring/react-spring-examples#40]
small docs issue re typescript

the examples on the main site don't work with typescript, I was wondering what the fix is for:

eg https://codesandbox.io/embed/01yl7knw70

```
      <a.div class="c back" style={{ opacity: opacity.interpolate(o => 1 - o), transform }} />
```

gives:
The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

![image](https://user-images.githubusercontent.com/514002/90761048-a7b7c880-e297-11ea-9704-86b1a466b91d.png)

adding an `any` typing to the `o` param fixed it

```
        style={{ opacity: opacity.interpolate((o: any) => 1 - o), transform }}
```

**Comment by litoriawynk** [comment]
but this defeats the whole purpose...is there any other way.

**Comment by aleclarson** [comment]
That error is fixed in v9.

**Comment by litoriawynk** [comment]
@aleclarson can you please show me an example to do the same
